// <auto-generated />
// Source: ../LazyForza.RaceServer/protocol/race-protocol.schema.json (SHA-256 1c6018c20f146d0effabe8456b52f27de2afb642f11dbd153bc18f9d1a1d0238)
#nullable enable

namespace LazyForza.Modules.EstateRace;

public static class EstateRaceProtocol
{
    public const int CurrentVersion = 2;
    public const int MaximumParticipants = 12;
    public const int MaximumObservers = 12;
    public const int MaximumMessageBytes = 64 * 1024;
    public const int MaximumDisplayNameLength = 20;
    public const int MaximumTeamNameLength = 24;
}

internal static class EstateRaceMessageTypes
{
    public const string Login = "login";
    public const string LoginAccepted = "loginAccepted";
    public const string LoginRejected = "loginRejected";
    public const string Ready = "ready";
    public const string Telemetry = "telemetry";
    public const string LapCompleted = "lapCompleted";
    public const string LapAcknowledged = "lapAcknowledged";
    public const string PitServiceCompleted = "pitServiceCompleted";
    public const string PitServiceAcknowledged = "pitServiceAcknowledged";
    public const string Snapshot = "snapshot";
    public const string Ping = "ping";
    public const string Pong = "pong";
    public const string Error = "error";
}

public enum RaceSessionPhase
{
    Lobby,
    Practice,
    Qualifying,
    Grid,
    OutLap,
    FormationLap,
    Countdown,
    Race,
    Suspended,
    Finished
}

public enum RaceControlFlag
{
    Green,
    Yellow,
    Red,
    Chequered
}

public enum RaceParticipantStatus
{
    Connected,
    Ready,
    OnTrack,
    InPitLane,
    InService,
    Finished,
    DidNotFinish,
    Disqualified,
    Disconnected
}

public enum RaceGripCondition
{
    Unknown,
    SlightlyReduced,
    ModeratelyReduced,
    SeverelyReduced,
    AtLimit
}

public enum RacePenaltyKind
{
    Warning,
    Time,
    DriveThrough,
    StopAndGo,
    GridDrop,
    Disqualification
}

public enum RaceBannerKind
{
    Information,
    FastestLap,
    Penalty,
    YellowFlag,
    RedFlag,
    BlueFlag,
    ChequeredFlag,
    Winner
}

public enum RaceInvestigationStatus
{
    Pending,
    Penalized,
    Dismissed
}

public sealed record EstateRaceServerDescriptor(
    string ServerName,
    int ProtocolVersion,
    int MaximumParticipants,
    bool RequiresPassword,
    string? ActiveTrackId,
    string? ActiveTrackRevision,
    RaceSessionPhase Phase,
    DateTimeOffset ServerTime,
    string? ActiveTrackName = null,
    string? ActiveTrackPackageHash = null,
    bool AllowTeams = true,
    int SectorCount = 0,
    int DriversPerTeam = 6,
    IReadOnlyList<EstateRaceTeam>? Teams = null,
    bool TrackPackageAvailable = false,
    long? TrackPackageSizeBytes = null,
    string? TrackPackageDownloadPath = null,
    string? TrackPackageFileSha256 = null,
    string? OrganizerLogoHash = null,
    string? OrganizerLogoMimeType = null,
    string? OrganizerLogoDownloadPath = null,
    bool SupportsObservers = false,
    int MaximumObservers = 0);

public sealed partial record EstateRaceTeam(
    string Id,
    string Name,
    string ThemeColor);

internal sealed record RaceLoginRequest(
    string Password,
    string DisplayName,
    string ThemeColor,
    string? TeamName,
    string ClientVersion,
    string? ResumeToken,
    string? TrackId,
    string? TrackRevision,
    string? TrackPackageHash,
    int? SectorCount = null,
    string? TeamId = null,
    bool IsObserver = false);

internal sealed record RaceLoginAccepted(
    Guid ParticipantId,
    string ResumeToken,
    EstateRaceSession Snapshot,
    DateTimeOffset ServerTime,
    bool IsObserver = false);

internal sealed record RaceLoginRejected(
    string Code,
    string Message);

internal sealed record RaceReadyUpdate(
    bool IsReady);

internal sealed record RaceClockPing(
    long ClientMonotonicMilliseconds);

internal sealed record RaceClockPong(
    long ClientMonotonicMilliseconds,
    long ServerUnixMilliseconds);

internal sealed record RaceTelemetryUpdate(
    long ClientMonotonicMilliseconds,
    double TrackProgress,
    double LateralOffsetMeters,
    double MapX,
    double MapY,
    double SpeedKph,
    int CompletedLaps,
    int CurrentSector,
    double CurrentLapSeconds,
    bool IsInPitLane,
    bool IsInServiceZone,
    bool IsTelemetryValid,
    bool IsPausedOrRewinding,
    RaceGripCondition GripCondition,
    double PitServiceElapsedSeconds,
    bool PitServiceRequirementMet,
    int CompletedPitServices,
    double TrackToleranceMeters = 18,
    double TrackLengthMeters = 0,
    double PitSpeedLimitKph = 0,
    double PitLaneElapsedSeconds = 0,
    bool IsApproachingPit = false,
    bool IsOnPitRoute = false,
    bool HasWorldPosition = false,
    double WorldX = 0,
    double WorldY = 0,
    double WorldZ = 0,
    double VelocityX = 0,
    double VelocityY = 0,
    double VelocityZ = 0,
    long ImpactSequence = 0,
    double ImpactMagnitudeMps = 0,
    double ImpactSpeedLossMps = 0,
    double ImpactWorldX = 0,
    double ImpactWorldY = 0,
    double ImpactWorldZ = 0,
    int ImpactAgeMilliseconds = 0,
    bool HasWorldVelocity = false,
    double WorldVelocityX = 0,
    double WorldVelocityY = 0,
    double WorldVelocityZ = 0,
    double ImpactWorldVelocityX = 0,
    double ImpactWorldVelocityY = 0,
    double ImpactWorldVelocityZ = 0,
    double ImpactSmashableVelDiff = 0,
    double ImpactSmashableMass = 0,
    RaceShortcutEvidence? ShortcutEvidence = null,
    Guid? PitServiceVisitId = null);

internal sealed record RaceShortcutEvidence(
    Guid Id,
    long DetectedAtMonotonicMilliseconds,
    double StartProgress,
    double EndProgress,
    double RouteDistanceMeters,
    double WorldDistanceMeters,
    double GainMeters,
    double MaximumLateralOffsetMeters,
    double ProtectedRouteMeters,
    double TheoreticalSavingMeters,
    int MissedCriticalGates,
    double Confidence,
    int Flags);

internal sealed record RaceLapCompleted(
    Guid EventId,
    int LapNumber,
    double LapSeconds,
    IReadOnlyList<double> SectorSeconds,
    bool IsValid,
    string? InvalidReason,
    long ClientMonotonicMilliseconds,
    bool IsBestLapEligible = true,
    bool IsRecoveredAfterDisconnect = false);

internal sealed record RaceLapAcknowledgement(
    Guid EventId,
    bool IsAccepted,
    string? Message = null);

internal sealed record RacePitServiceCompleted(
    Guid EventId,
    Guid VisitId,
    int CompletedPitServices,
    double RequiredSeconds,
    double ElapsedSeconds,
    long ClientMonotonicMilliseconds,
    long RaceStartedAtUnixMilliseconds,
    bool IsRecoveredAfterDisconnect = false);

internal sealed record RacePitServiceAcknowledgement(
    Guid EventId,
    bool IsAccepted,
    string? Message = null);

internal sealed record RaceProtocolError(
    string Code,
    string Message);

public sealed record EstateRacePenalty(
    Guid Id,
    RacePenaltyKind Kind,
    double? ValueSeconds,
    int? GridPlaces,
    string Reason,
    bool IsServed,
    bool IsRevoked,
    bool IsPostRaceAdjustment = false,
    bool IsAutomatic = false,
    Guid? InvestigationId = null);

public sealed record EstateRaceInvestigation(
    Guid Id,
    Guid ParticipantId,
    string Offense,
    DateTimeOffset DetectedAt,
    int LapNumber,
    RaceInvestigationStatus Status,
    Guid? PenaltyId = null,
    DateTimeOffset? ResolvedAt = null,
    IReadOnlyList<Guid>? RelatedParticipantIds = null,
    EstateCollisionEvidenceSnapshot? CollisionEvidence = null);

public sealed record EstateCollisionEvidenceSnapshot(
    DateTimeOffset IncidentAt,
    Guid ReporterParticipantId,
    Guid OtherParticipantId,
    string ReporterName,
    string OtherName,
    string ReporterThemeColor,
    string OtherThemeColor,
    double ReporterWorldX,
    double ReporterWorldY,
    double ReporterWorldZ,
    double OtherWorldX,
    double OtherWorldY,
    double OtherWorldZ,
    double ReporterVelocityX,
    double ReporterVelocityZ,
    double OtherVelocityX,
    double OtherVelocityZ,
    double HorizontalDistanceMeters,
    double VerticalDistanceMeters,
    double RelativeSpeedKph,
    double ImpactMagnitudeMps,
    double ImpactSpeedLossMps,
    double ApproachDistanceReductionMeters = 0,
    bool BothDriversReportedImpact = false,
    int ContactCount = 1,
    DateTimeOffset? LastIncidentAt = null);

public sealed record EstateRaceParticipant(
    Guid Id,
    int Position,
    string DisplayName,
    string ThemeColor,
    string? TeamName,
    RaceParticipantStatus Status,
    bool IsConnected,
    bool IsReady,
    int CompletedLaps,
    int CurrentSector,
    double TrackProgress,
    double MapX,
    double MapY,
    double SpeedKph,
    double CurrentLapSeconds,
    double? LastLapSeconds,
    double? BestLapSeconds,
    double? GapToLeaderSeconds,
    double? IntervalSeconds,
    bool IsInPitLane,
    bool IsInServiceZone,
    double PitServiceElapsedSeconds,
    bool PitServiceRequirementMet,
    int CompletedPitServices,
    RaceGripCondition GripCondition,
    IReadOnlyList<double?> BestSectorSeconds,
    IReadOnlyList<EstateRacePenalty> Penalties,
    DateTimeOffset LastSeenAt,
    bool QualifyingFinalLapPending = false,
    double? RaceTotalSeconds = null,
    double? AdjustedRaceTotalSeconds = null,
    double TimePenaltySeconds = 0,
    int TrackLimitWarnings = 0,
    string? TeamId = null,
    string? TeamColor = null,
    double PitLaneElapsedSeconds = 0,
    double PendingTimePenaltySeconds = 0,
    bool IsServingTimePenalty = false,
    double PenaltyServiceElapsedSeconds = 0,
    double PenaltyServiceRequiredSeconds = 0,
    bool HasPendingDriveThrough = false,
    bool PenaltyServiceCompleted = false,
    int? DriveThroughLapsRemaining = null,
    DateTimeOffset? DriveThroughReminderAt = null,
    bool DriveThroughOverdue = false,
    bool IsServingDriveThrough = false,
    bool QualifyingEligible = true,
    int? QualifyingEliminatedInSession = null,
    IReadOnlyList<double?>? QualifyingSessionBestLapSeconds = null,
    bool PracticeFinalLapPending = false,
    IReadOnlyList<double?>? PracticeSessionBestLapSeconds = null,
    IReadOnlyDictionary<Guid, double>? RaceDeltaSecondsByReference = null);

public sealed record EstateRaceObserver(
    Guid Id,
    string DisplayName,
    DateTimeOffset ConnectedAt);

public sealed record EstateRaceBanner(
    Guid Id,
    RaceBannerKind Kind,
    string Title,
    string? Detail,
    Guid? ParticipantId,
    DateTimeOffset CreatedAt,
    DateTimeOffset? ExpiresAt,
    bool IsInvestigation = false);

public sealed record EstateRaceYellowZone(
    int? SectorIndex,
    bool IsAutomatic,
    string Reason,
    Guid? ParticipantId,
    string? ParticipantName);

public sealed record EstateRaceBlueFlag(
    Guid RecipientParticipantId,
    Guid ApproachingParticipantId,
    double DistanceAhead);

public sealed record EstateRaceSession(
    long Revision,
    string SessionName,
    RaceSessionPhase Phase,
    RaceControlFlag Flag,
    string? FlagMessage,
    string? TrackId,
    string? TrackRevision,
    string? TrackPackageHash,
    int TotalRaceLaps,
    DateTimeOffset? StartsAt,
    DateTimeOffset? QualifyingEndsAt,
    Guid? FastestParticipantId,
    double? FastestLapSeconds,
    IReadOnlyList<double?> FastestSectorSeconds,
    EstateRaceBanner? Banner,
    IReadOnlyList<EstateRaceParticipant> Participants,
    DateTimeOffset ServerTime,
    IReadOnlyList<EstateRaceYellowZone>? YellowZones = null,
    int SectorCount = 0,
    bool AllowTeams = true,
    string? TrackName = null,
    IReadOnlyList<EstateRaceBlueFlag>? BlueFlags = null,
    DateTimeOffset? StartSequenceAt = null,
    int IlluminatedStartLights = 0,
    bool StartLightsOut = false,
    bool QualifyingTimeExpired = false,
    double? RaceElapsedSeconds = null,
    RaceSessionPhase? SuspendedFromPhase = null,
    int DriversPerTeam = 6,
    IReadOnlyList<EstateRaceTeam>? Teams = null,
    bool ChequeredImminent = false,
    IReadOnlyList<double?>? FastestLapSectorSeconds = null,
    string? OrganizerLogoHash = null,
    string? OrganizerLogoMimeType = null,
    string? OrganizerLogoDownloadPath = null,
    IReadOnlyList<EstateRacePenalty>? Penalties = null,
    IReadOnlyList<EstateRaceInvestigation>? Investigations = null,
    int QualifyingSessionNumber = 0,
    int QualifyingSessionCount = 1,
    IReadOnlyList<int>? QualifyingSessionMinutes = null,
    IReadOnlyList<int>? QualifyingEliminationCounts = null,
    DateTimeOffset? PracticeEndsAt = null,
    bool PracticeTimeExpired = false,
    int PracticeSessionNumber = 0,
    int PracticeSessionCount = 1,
    IReadOnlyList<int>? PracticeSessionMinutes = null,
    IReadOnlyList<EstateRaceObserver>? Observers = null,
    int MinimumRequiredPitStops = 1,
    bool DisconnectedLapRecoveryEnabled = false);

